///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OtpVerificationModelData {
/*
{
  "cus_id": 1,
  "cus_first_name": "Hardik",
  "cus_last_name": "Vyas",
  "cus_profile_pic": null,
  "cus_mobile": "9724558884",
  "cus_email": "vyas.hardik05@gmail.com",
  "cus_password": null,
  "cus_created_on": null,
  "cus_updated_on": null,
  "cus_refferal_code": null,
  "cus_refer_by": 0,
  "cus_is_active": null,
  "cus_remark": null,
  "cust_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiOTcyNDU1ODg4NCIsInJvbGUiOiJTZWxsZXIiLCJzZWxsZXJfaWQiOiIxIiwic2VsbGVyX2Z1bGxfbmFtZSI6IkhhcmRpayIsInNlbGxlcl9tb2JpbGUiOiI5NzI0NTU4ODg0Iiwic2VsbGVyX2VtYWlsIjoidnlhcy5oYXJkaWswNUBnbWFpbC5jb20iLCJuYmYiOjE2NTQ1Mzg1NjEsImV4cCI6MTY1NDU4MTc2MSwiaWF0IjoxNjU0NTM4NTYxfQ.7ZlZRRFv6axwb6DTYEs4tC4sBZTepdW8iAukSzu614A",
  "cus_otp": null
}
*/

  int? cusId;
  String? cusFirstName;
  String? cusLastName;
  String? cusProfilePic;
  String? cusMobile;
  String? cusEmail;
  String? cusPassword;
  String? cusCreatedOn;
  String? cusUpdatedOn;
  String? cusRefferalCode;
  int? cusReferBy;
  String? cusIsActive;
  String? cusRemark;
  String? custToken;
  String? cusOtp;

  OtpVerificationModelData({
    this.cusId,
    this.cusFirstName,
    this.cusLastName,
    this.cusProfilePic,
    this.cusMobile,
    this.cusEmail,
    this.cusPassword,
    this.cusCreatedOn,
    this.cusUpdatedOn,
    this.cusRefferalCode,
    this.cusReferBy,
    this.cusIsActive,
    this.cusRemark,
    this.custToken,
    this.cusOtp,
  });
  OtpVerificationModelData.fromJson(Map<String, dynamic> json) {
    cusId = json['cus_id']?.toInt();
    cusFirstName = json['cus_first_name']?.toString();
    cusLastName = json['cus_last_name']?.toString();
    cusProfilePic = json['cus_profile_pic']?.toString();
    cusMobile = json['cus_mobile']?.toString();
    cusEmail = json['cus_email']?.toString();
    cusPassword = json['cus_password']?.toString();
    cusCreatedOn = json['cus_created_on']?.toString();
    cusUpdatedOn = json['cus_updated_on']?.toString();
    cusRefferalCode = json['cus_refferal_code']?.toString();
    cusReferBy = json['cus_refer_by']?.toInt();
    cusIsActive = json['cus_is_active']?.toString();
    cusRemark = json['cus_remark']?.toString();
    custToken = json['cust_token']?.toString();
    cusOtp = json['cus_otp']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cus_id'] = cusId;
    data['cus_first_name'] = cusFirstName;
    data['cus_last_name'] = cusLastName;
    data['cus_profile_pic'] = cusProfilePic;
    data['cus_mobile'] = cusMobile;
    data['cus_email'] = cusEmail;
    data['cus_password'] = cusPassword;
    data['cus_created_on'] = cusCreatedOn;
    data['cus_updated_on'] = cusUpdatedOn;
    data['cus_refferal_code'] = cusRefferalCode;
    data['cus_refer_by'] = cusReferBy;
    data['cus_is_active'] = cusIsActive;
    data['cus_remark'] = cusRemark;
    data['cust_token'] = custToken;
    data['cus_otp'] = cusOtp;
    return data;
  }
}

class OtpVerificationModel {
/*
{
  "Code": 1,
  "Message": "",
  "Data": {
    "cus_id": 1,
    "cus_first_name": "Hardik",
    "cus_last_name": "Vyas",
    "cus_profile_pic": null,
    "cus_mobile": "9724558884",
    "cus_email": "vyas.hardik05@gmail.com",
    "cus_password": null,
    "cus_created_on": null,
    "cus_updated_on": null,
    "cus_refferal_code": null,
    "cus_refer_by": 0,
    "cus_is_active": null,
    "cus_remark": null,
    "cust_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiOTcyNDU1ODg4NCIsInJvbGUiOiJTZWxsZXIiLCJzZWxsZXJfaWQiOiIxIiwic2VsbGVyX2Z1bGxfbmFtZSI6IkhhcmRpayIsInNlbGxlcl9tb2JpbGUiOiI5NzI0NTU4ODg0Iiwic2VsbGVyX2VtYWlsIjoidnlhcy5oYXJkaWswNUBnbWFpbC5jb20iLCJuYmYiOjE2NTQ1Mzg1NjEsImV4cCI6MTY1NDU4MTc2MSwiaWF0IjoxNjU0NTM4NTYxfQ.7ZlZRRFv6axwb6DTYEs4tC4sBZTepdW8iAukSzu614A",
    "cus_otp": null
  }
}
*/

  int? Code;
  String? Message;
  OtpVerificationModelData? Data;

  OtpVerificationModel({
    this.Code,
    this.Message,
    this.Data,
  });
  OtpVerificationModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? OtpVerificationModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
