///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyOrderHistoryModelData {
/*
{
  "ord_id": 1,
  "ord_orh_id": 0,
  "ord_key": 0,
  "ord_no": "1",
  "ord_cus_id": 0,
  "ord_cadd_id": 0,
  "ord_seller_id": 0,
  "ord_date": "2022-06-30T00:29:45.753",
  "ord_osts_id": 1,
  "ord_itm_id": 0,
  "ord_isku_id": 0,
  "ord_mrp": 0,
  "ord_selling_price": 0,
  "ord_qty": 0,
  "ord_amount": 0,
  "ord_is_return": null,
  "ord_coupon_id": 0,
  "ord_coupon_discount_per": 0,
  "ord_coupon_discount_amount": 0,
  "ord_delivery_fees": 0,
  "ord_grand_total": 295.2,
  "ord_instruction": null,
  "ord_is_paid": true,
  "ord_pgc_id": 0,
  "ord_transaction_no": "lkj3lk4j3lk4j",
  "ord_total_savings": 0,
  "cus_first_name": "Hardik Vyas",
  "ct_name": "Kolkata - West Bengal",
  "cadd_pincode": "390012",
  "osts_name": "Order Placed",
  "pgc_name": "RazorPay",
  "seller_display_name": "A & B Co.",
  "isku_image_1": "http://rohan4-001-site1.ftempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
  "itm_name": "Polo Tshirt Pure Cotton",
  "primary_var_name": "Size",
  "secondary_var_name": "Colour",
  "primary_varo_name": "S",
  "secondary_varo_name": "Black"
}
*/

  int? ordId;
  int? ordOrhId;
  int? ordKey;
  String? ordNo;
  int? ordCusId;
  int? ordCaddId;
  int? ordSellerId;
  String? ordDate;
  int? ordOstsId;
  int? ordItmId;
  int? ordIskuId;
  int? ordMrp;
  int? ordSellingPrice;
  int? ordQty;
  int? ordAmount;
  String? ordIsReturn;
  int? ordCouponId;
  int? ordCouponDiscountPer;
  int? ordCouponDiscountAmount;
  int? ordDeliveryFees;
  double? ordGrandTotal;
  String? ordInstruction;
  bool? ordIsPaid;
  int? ordPgcId;
  String? ordTransactionNo;
  int? ordTotalSavings;
  String? cusFirstName;
  String? ctName;
  String? caddPincode;
  String? ostsName;
  String? pgcName;
  String? sellerDisplayName;
  String? iskuImage_1;
  String? itmName;
  String? primaryVarName;
  String? secondaryVarName;
  String? primaryVaroName;
  String? secondaryVaroName;

  MyOrderHistoryModelData({
    this.ordId,
    this.ordOrhId,
    this.ordKey,
    this.ordNo,
    this.ordCusId,
    this.ordCaddId,
    this.ordSellerId,
    this.ordDate,
    this.ordOstsId,
    this.ordItmId,
    this.ordIskuId,
    this.ordMrp,
    this.ordSellingPrice,
    this.ordQty,
    this.ordAmount,
    this.ordIsReturn,
    this.ordCouponId,
    this.ordCouponDiscountPer,
    this.ordCouponDiscountAmount,
    this.ordDeliveryFees,
    this.ordGrandTotal,
    this.ordInstruction,
    this.ordIsPaid,
    this.ordPgcId,
    this.ordTransactionNo,
    this.ordTotalSavings,
    this.cusFirstName,
    this.ctName,
    this.caddPincode,
    this.ostsName,
    this.pgcName,
    this.sellerDisplayName,
    this.iskuImage_1,
    this.itmName,
    this.primaryVarName,
    this.secondaryVarName,
    this.primaryVaroName,
    this.secondaryVaroName,
  });
  MyOrderHistoryModelData.fromJson(Map<String, dynamic> json) {
    ordId = json['ord_id']?.toInt();
    ordOrhId = json['ord_orh_id']?.toInt();
    ordKey = json['ord_key']?.toInt();
    ordNo = json['ord_no']?.toString();
    ordCusId = json['ord_cus_id']?.toInt();
    ordCaddId = json['ord_cadd_id']?.toInt();
    ordSellerId = json['ord_seller_id']?.toInt();
    ordDate = json['ord_date']?.toString();
    ordOstsId = json['ord_osts_id']?.toInt();
    ordItmId = json['ord_itm_id']?.toInt();
    ordIskuId = json['ord_isku_id']?.toInt();
    ordMrp = json['ord_mrp']?.toInt();
    ordSellingPrice = json['ord_selling_price']?.toInt();
    ordQty = json['ord_qty']?.toInt();
    ordAmount = json['ord_amount']?.toInt();
    ordIsReturn = json['ord_is_return']?.toString();
    ordCouponId = json['ord_coupon_id']?.toInt();
    ordCouponDiscountPer = json['ord_coupon_discount_per']?.toInt();
    ordCouponDiscountAmount = json['ord_coupon_discount_amount']?.toInt();
    ordDeliveryFees = json['ord_delivery_fees']?.toInt();
    ordGrandTotal = json['ord_grand_total']?.toDouble();
    ordInstruction = json['ord_instruction']?.toString();
    ordIsPaid = json['ord_is_paid'];
    ordPgcId = json['ord_pgc_id']?.toInt();
    ordTransactionNo = json['ord_transaction_no']?.toString();
    ordTotalSavings = json['ord_total_savings']?.toInt();
    cusFirstName = json['cus_first_name']?.toString();
    ctName = json['ct_name']?.toString();
    caddPincode = json['cadd_pincode']?.toString();
    ostsName = json['osts_name']?.toString();
    pgcName = json['pgc_name']?.toString();
    sellerDisplayName = json['seller_display_name']?.toString();
    iskuImage_1 = json['isku_image_1']?.toString();
    itmName = json['itm_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    primaryVaroName = json['primary_varo_name']?.toString();
    secondaryVaroName = json['secondary_varo_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ord_id'] = ordId;
    data['ord_orh_id'] = ordOrhId;
    data['ord_key'] = ordKey;
    data['ord_no'] = ordNo;
    data['ord_cus_id'] = ordCusId;
    data['ord_cadd_id'] = ordCaddId;
    data['ord_seller_id'] = ordSellerId;
    data['ord_date'] = ordDate;
    data['ord_osts_id'] = ordOstsId;
    data['ord_itm_id'] = ordItmId;
    data['ord_isku_id'] = ordIskuId;
    data['ord_mrp'] = ordMrp;
    data['ord_selling_price'] = ordSellingPrice;
    data['ord_qty'] = ordQty;
    data['ord_amount'] = ordAmount;
    data['ord_is_return'] = ordIsReturn;
    data['ord_coupon_id'] = ordCouponId;
    data['ord_coupon_discount_per'] = ordCouponDiscountPer;
    data['ord_coupon_discount_amount'] = ordCouponDiscountAmount;
    data['ord_delivery_fees'] = ordDeliveryFees;
    data['ord_grand_total'] = ordGrandTotal;
    data['ord_instruction'] = ordInstruction;
    data['ord_is_paid'] = ordIsPaid;
    data['ord_pgc_id'] = ordPgcId;
    data['ord_transaction_no'] = ordTransactionNo;
    data['ord_total_savings'] = ordTotalSavings;
    data['cus_first_name'] = cusFirstName;
    data['ct_name'] = ctName;
    data['cadd_pincode'] = caddPincode;
    data['osts_name'] = ostsName;
    data['pgc_name'] = pgcName;
    data['seller_display_name'] = sellerDisplayName;
    data['isku_image_1'] = iskuImage_1;
    data['itm_name'] = itmName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    data['primary_varo_name'] = primaryVaroName;
    data['secondary_varo_name'] = secondaryVaroName;
    return data;
  }
}

class MyOrderHistoryModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "ord_id": 1,
      "ord_orh_id": 0,
      "ord_key": 0,
      "ord_no": "1",
      "ord_cus_id": 0,
      "ord_cadd_id": 0,
      "ord_seller_id": 0,
      "ord_date": "2022-06-30T00:29:45.753",
      "ord_osts_id": 1,
      "ord_itm_id": 0,
      "ord_isku_id": 0,
      "ord_mrp": 0,
      "ord_selling_price": 0,
      "ord_qty": 0,
      "ord_amount": 0,
      "ord_is_return": null,
      "ord_coupon_id": 0,
      "ord_coupon_discount_per": 0,
      "ord_coupon_discount_amount": 0,
      "ord_delivery_fees": 0,
      "ord_grand_total": 295.2,
      "ord_instruction": null,
      "ord_is_paid": true,
      "ord_pgc_id": 0,
      "ord_transaction_no": "lkj3lk4j3lk4j",
      "ord_total_savings": 0,
      "cus_first_name": "Hardik Vyas",
      "ct_name": "Kolkata - West Bengal",
      "cadd_pincode": "390012",
      "osts_name": "Order Placed",
      "pgc_name": "RazorPay",
      "seller_display_name": "A & B Co.",
      "isku_image_1": "http://rohan4-001-site1.ftempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
      "itm_name": "Polo Tshirt Pure Cotton",
      "primary_var_name": "Size",
      "secondary_var_name": "Colour",
      "primary_varo_name": "S",
      "secondary_varo_name": "Black"
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<MyOrderHistoryModelData?>? Data;

  MyOrderHistoryModel({
    this.Code,
    this.Message,
    this.Data,
  });
  MyOrderHistoryModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <MyOrderHistoryModelData>[];
      v.forEach((v) {
        arr0.add(MyOrderHistoryModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
