///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelData {
/*
{
  "cat_id": 8,
  "cat_parent_id": 7,
  "cat_name": "Tshirts",
  "cat_image": "http://hardik5165-001-site1.itempurl.com/Documents/white-tee-1623337322_02062022113542.jpg",
  "cat_is_active": true,
  "created_by": "Hardik Vyas",
  "created_date": "2022-04-30T04:36:38.217",
  "updated_by": "Hardik Vyas",
  "updated_date": "2022-06-02T23:35:43.253",
  "cat_parent_name": "Mens Fashions",
  "cat_main_name": "Fashion",
  "cat_main_id": 2
}
*/

  int? catId;
  int? catParentId;
  String? catName;
  String? catImage;
  bool? catIsActive;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  String? catParentName;
  String? catMainName;
  int? catMainId;

  ProductModelData({
    this.catId,
    this.catParentId,
    this.catName,
    this.catImage,
    this.catIsActive,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.catParentName,
    this.catMainName,
    this.catMainId,
  });
  ProductModelData.fromJson(Map<String, dynamic> json) {
    catId = json['cat_id']?.toInt();
    catParentId = json['cat_parent_id']?.toInt();
    catName = json['cat_name']?.toString();
    catImage = json['cat_image']?.toString();
    catIsActive = json['cat_is_active'];
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    catParentName = json['cat_parent_name']?.toString();
    catMainName = json['cat_main_name']?.toString();
    catMainId = json['cat_main_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cat_id'] = catId;
    data['cat_parent_id'] = catParentId;
    data['cat_name'] = catName;
    data['cat_image'] = catImage;
    data['cat_is_active'] = catIsActive;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['cat_parent_name'] = catParentName;
    data['cat_main_name'] = catMainName;
    data['cat_main_id'] = catMainId;
    return data;
  }
}

class ProductModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "cat_id": 8,
      "cat_parent_id": 7,
      "cat_name": "Tshirts",
      "cat_image": "http://hardik5165-001-site1.itempurl.com/Documents/white-tee-1623337322_02062022113542.jpg",
      "cat_is_active": true,
      "created_by": "Hardik Vyas",
      "created_date": "2022-04-30T04:36:38.217",
      "updated_by": "Hardik Vyas",
      "updated_date": "2022-06-02T23:35:43.253",
      "cat_parent_name": "Mens Fashions",
      "cat_main_name": "Fashion",
      "cat_main_id": 2
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<ProductModelData?>? Data;

  ProductModel({
    this.Code,
    this.Message,
    this.Data,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <ProductModelData>[];
      v.forEach((v) {
        arr0.add(ProductModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
