///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAddressModelData {
/*
{
  "cadd_id": 1,
  "cadd_cus_id": 1,
  "cadd_address_name": "Home",
  "cadd_house_no": "B-18",
  "cadd_address_1": "Samarpan Hou Complex",
  "cadd_address_2": "B/h Raneshwar Temple",
  "cadd_address_3": "Vasna Road",
  "cadd_pincode": "390012",
  "cadd_ct_id": 2,
  "cadd_st_id": 3,
  "cadd_cnt_id": 1,
  "cadd_is_default": false,
  "cnt_name": "India",
  "st_name": "West Bengal",
  "ct_name": "Kolkata"
}
*/

  int? caddId;
  int? caddCusId;
  String? caddAddressName;
  String? caddHouseNo;
  String? caddAddress_1;
  String? caddAddress_2;
  String? caddAddress_3;
  String? caddPincode;
  int? caddCtId;
  int? caddStId;
  int? caddCntId;
  bool? caddIsDefault;
  String? cntName;
  String? stName;
  String? ctName;

  GetAddressModelData({
    this.caddId,
    this.caddCusId,
    this.caddAddressName,
    this.caddHouseNo,
    this.caddAddress_1,
    this.caddAddress_2,
    this.caddAddress_3,
    this.caddPincode,
    this.caddCtId,
    this.caddStId,
    this.caddCntId,
    this.caddIsDefault,
    this.cntName,
    this.stName,
    this.ctName,
  });
  GetAddressModelData.fromJson(Map<String, dynamic> json) {
    caddId = json['cadd_id']?.toInt();
    caddCusId = json['cadd_cus_id']?.toInt();
    caddAddressName = json['cadd_address_name']?.toString();
    caddHouseNo = json['cadd_house_no']?.toString();
    caddAddress_1 = json['cadd_address_1']?.toString();
    caddAddress_2 = json['cadd_address_2']?.toString();
    caddAddress_3 = json['cadd_address_3']?.toString();
    caddPincode = json['cadd_pincode']?.toString();
    caddCtId = json['cadd_ct_id']?.toInt();
    caddStId = json['cadd_st_id']?.toInt();
    caddCntId = json['cadd_cnt_id']?.toInt();
    caddIsDefault = json['cadd_is_default'];
    cntName = json['cnt_name']?.toString();
    stName = json['st_name']?.toString();
    ctName = json['ct_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cadd_id'] = caddId;
    data['cadd_cus_id'] = caddCusId;
    data['cadd_address_name'] = caddAddressName;
    data['cadd_house_no'] = caddHouseNo;
    data['cadd_address_1'] = caddAddress_1;
    data['cadd_address_2'] = caddAddress_2;
    data['cadd_address_3'] = caddAddress_3;
    data['cadd_pincode'] = caddPincode;
    data['cadd_ct_id'] = caddCtId;
    data['cadd_st_id'] = caddStId;
    data['cadd_cnt_id'] = caddCntId;
    data['cadd_is_default'] = caddIsDefault;
    data['cnt_name'] = cntName;
    data['st_name'] = stName;
    data['ct_name'] = ctName;
    return data;
  }
}

class GetAddressModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "cadd_id": 1,
      "cadd_cus_id": 1,
      "cadd_address_name": "Home",
      "cadd_house_no": "B-18",
      "cadd_address_1": "Samarpan Hou Complex",
      "cadd_address_2": "B/h Raneshwar Temple",
      "cadd_address_3": "Vasna Road",
      "cadd_pincode": "390012",
      "cadd_ct_id": 2,
      "cadd_st_id": 3,
      "cadd_cnt_id": 1,
      "cadd_is_default": false,
      "cnt_name": "India",
      "st_name": "West Bengal",
      "ct_name": "Kolkata"
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<GetAddressModelData?>? Data;

  GetAddressModel({
    this.Code,
    this.Message,
    this.Data,
  });
  GetAddressModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <GetAddressModelData>[];
      v.forEach((v) {
        arr0.add(GetAddressModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
