///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SetOrderModelData {
/*
{
  "ord_orh_id": 14,
  "ord_grand_total": 0
}
*/

  int? ordOrhId;
  int? ordGrandTotal;

  SetOrderModelData({
    this.ordOrhId,
    this.ordGrandTotal,
  });
  SetOrderModelData.fromJson(Map<String, dynamic> json) {
    ordOrhId = json['ord_orh_id']?.toInt();
    ordGrandTotal = json['ord_grand_total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ord_orh_id'] = ordOrhId;
    data['ord_grand_total'] = ordGrandTotal;
    return data;
  }
}

class SetOrderModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": {
    "ord_orh_id": 14,
    "ord_grand_total": 0
  }
}
*/

  int? Code;
  String? Message;
  SetOrderModelData? Data;

  SetOrderModel({
    this.Code,
    this.Message,
    this.Data,
  });
  SetOrderModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? SetOrderModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
