///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAllActiveDealsOfTheDayModelData {
/*
{
  "isku_id": 1,
  "isku_itm_id": 1,
  "isku_primary_varo_id": 0,
  "isku_secondary_varo_id": 0,
  "isku_uom_id": 0,
  "isku_images": null,
  "isku_image_1": "http://rohan4-001-site1.ftempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
  "isku_image_2": null,
  "isku_image_3": null,
  "isku_image_4": null,
  "isku_image_5": null,
  "isku_mrp": 200,
  "isku_offer_price": 180,
  "isku_is_active": null,
  "is_variant_available": null,
  "created_by": null,
  "created_date": null,
  "updated_by": null,
  "updated_date": null,
  "itm_name": "Polo Tshirt Pure Cotton",
  "primary_var_name": "Size",
  "secondary_var_name": "Colour",
  "primary_varo_name": "S",
  "secondary_varo_name": "Black",
  "idod_valid_from": "2021-11-23T03:16:00",
  "idod_valid_to": "2022-11-25T01:06:00",
  "idod_is_active": true,
  "ifeat_valid_from": null,
  "ifeat_valid_to": null,
  "ifeat_is_active": null,
  "cat_name": null,
  "itemVariationDetailsModels": null,
  "sstk_seller_id": 1,
  "sstk_qty": 25,
  "isAddedToWishList": false
}
*/

  int? iskuId;
  int? iskuItmId;
  int? iskuPrimaryVaroId;
  int? iskuSecondaryVaroId;
  int? iskuUomId;
  String? iskuImages;
  String? iskuImage_1;
  String? iskuImage_2;
  String? iskuImage_3;
  String? iskuImage_4;
  String? iskuImage_5;
  int? iskuMrp;
  int? iskuOfferPrice;
  String? iskuIsActive;
  String? isVariantAvailable;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  String? itmName;
  String? primaryVarName;
  String? secondaryVarName;
  String? primaryVaroName;
  String? secondaryVaroName;
  String? idodValidFrom;
  String? idodValidTo;
  bool? idodIsActive;
  String? ifeatValidFrom;
  String? ifeatValidTo;
  String? ifeatIsActive;
  String? catName;
  String? itemVariationDetailsModels;
  int? sstkSellerId;
  int? sstkQty;
  bool? isAddedToWishList;

  GetAllActiveDealsOfTheDayModelData({
    this.iskuId,
    this.iskuItmId,
    this.iskuPrimaryVaroId,
    this.iskuSecondaryVaroId,
    this.iskuUomId,
    this.iskuImages,
    this.iskuImage_1,
    this.iskuImage_2,
    this.iskuImage_3,
    this.iskuImage_4,
    this.iskuImage_5,
    this.iskuMrp,
    this.iskuOfferPrice,
    this.iskuIsActive,
    this.isVariantAvailable,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.itmName,
    this.primaryVarName,
    this.secondaryVarName,
    this.primaryVaroName,
    this.secondaryVaroName,
    this.idodValidFrom,
    this.idodValidTo,
    this.idodIsActive,
    this.ifeatValidFrom,
    this.ifeatValidTo,
    this.ifeatIsActive,
    this.catName,
    this.itemVariationDetailsModels,
    this.sstkSellerId,
    this.sstkQty,
    this.isAddedToWishList,
  });
  GetAllActiveDealsOfTheDayModelData.fromJson(Map<String, dynamic> json) {
    iskuId = json['isku_id']?.toInt();
    iskuItmId = json['isku_itm_id']?.toInt();
    iskuPrimaryVaroId = json['isku_primary_varo_id']?.toInt();
    iskuSecondaryVaroId = json['isku_secondary_varo_id']?.toInt();
    iskuUomId = json['isku_uom_id']?.toInt();
    iskuImages = json['isku_images']?.toString();
    iskuImage_1 = json['isku_image_1']?.toString();
    iskuImage_2 = json['isku_image_2']?.toString();
    iskuImage_3 = json['isku_image_3']?.toString();
    iskuImage_4 = json['isku_image_4']?.toString();
    iskuImage_5 = json['isku_image_5']?.toString();
    iskuMrp = json['isku_mrp']?.toInt();
    iskuOfferPrice = json['isku_offer_price']?.toInt();
    iskuIsActive = json['isku_is_active']?.toString();
    isVariantAvailable = json['is_variant_available']?.toString();
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    itmName = json['itm_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    primaryVaroName = json['primary_varo_name']?.toString();
    secondaryVaroName = json['secondary_varo_name']?.toString();
    idodValidFrom = json['idod_valid_from']?.toString();
    idodValidTo = json['idod_valid_to']?.toString();
    idodIsActive = json['idod_is_active'];
    ifeatValidFrom = json['ifeat_valid_from']?.toString();
    ifeatValidTo = json['ifeat_valid_to']?.toString();
    ifeatIsActive = json['ifeat_is_active']?.toString();
    catName = json['cat_name']?.toString();
    itemVariationDetailsModels = json['itemVariationDetailsModels']?.toString();
    sstkSellerId = json['sstk_seller_id']?.toInt();
    sstkQty = json['sstk_qty']?.toInt();
    isAddedToWishList = json['isAddedToWishList'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isku_id'] = iskuId;
    data['isku_itm_id'] = iskuItmId;
    data['isku_primary_varo_id'] = iskuPrimaryVaroId;
    data['isku_secondary_varo_id'] = iskuSecondaryVaroId;
    data['isku_uom_id'] = iskuUomId;
    data['isku_images'] = iskuImages;
    data['isku_image_1'] = iskuImage_1;
    data['isku_image_2'] = iskuImage_2;
    data['isku_image_3'] = iskuImage_3;
    data['isku_image_4'] = iskuImage_4;
    data['isku_image_5'] = iskuImage_5;
    data['isku_mrp'] = iskuMrp;
    data['isku_offer_price'] = iskuOfferPrice;
    data['isku_is_active'] = iskuIsActive;
    data['is_variant_available'] = isVariantAvailable;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['itm_name'] = itmName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    data['primary_varo_name'] = primaryVaroName;
    data['secondary_varo_name'] = secondaryVaroName;
    data['idod_valid_from'] = idodValidFrom;
    data['idod_valid_to'] = idodValidTo;
    data['idod_is_active'] = idodIsActive;
    data['ifeat_valid_from'] = ifeatValidFrom;
    data['ifeat_valid_to'] = ifeatValidTo;
    data['ifeat_is_active'] = ifeatIsActive;
    data['cat_name'] = catName;
    data['itemVariationDetailsModels'] = itemVariationDetailsModels;
    data['sstk_seller_id'] = sstkSellerId;
    data['sstk_qty'] = sstkQty;
    data['isAddedToWishList'] = isAddedToWishList;
    return data;
  }
}

class GetAllActiveDealsOfTheDayModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "isku_id": 1,
      "isku_itm_id": 1,
      "isku_primary_varo_id": 0,
      "isku_secondary_varo_id": 0,
      "isku_uom_id": 0,
      "isku_images": null,
      "isku_image_1": "http://rohan4-001-site1.ftempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
      "isku_image_2": null,
      "isku_image_3": null,
      "isku_image_4": null,
      "isku_image_5": null,
      "isku_mrp": 200,
      "isku_offer_price": 180,
      "isku_is_active": null,
      "is_variant_available": null,
      "created_by": null,
      "created_date": null,
      "updated_by": null,
      "updated_date": null,
      "itm_name": "Polo Tshirt Pure Cotton",
      "primary_var_name": "Size",
      "secondary_var_name": "Colour",
      "primary_varo_name": "S",
      "secondary_varo_name": "Black",
      "idod_valid_from": "2021-11-23T03:16:00",
      "idod_valid_to": "2022-11-25T01:06:00",
      "idod_is_active": true,
      "ifeat_valid_from": null,
      "ifeat_valid_to": null,
      "ifeat_is_active": null,
      "cat_name": null,
      "itemVariationDetailsModels": null,
      "sstk_seller_id": 1,
      "sstk_qty": 25,
      "isAddedToWishList": false
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<GetAllActiveDealsOfTheDayModelData?>? Data;

  GetAllActiveDealsOfTheDayModel({
    this.Code,
    this.Message,
    this.Data,
  });
  GetAllActiveDealsOfTheDayModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <GetAllActiveDealsOfTheDayModelData>[];
      v.forEach((v) {
        arr0.add(GetAllActiveDealsOfTheDayModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
