///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetUnderPriceModelDataChildCategory {
/*
{
  "cat_id": 8,
  "cat_parent_id": 7,
  "cat_name": "Tshirts",
  "cat_image": "http://hardik5165-001-site1.itempurl.com/Documents/Category_30052022030255.jpg",
  "cat_is_active": true,
  "created_by": "Hardik Vyas",
  "created_date": "2022-04-30T04:36:38.217",
  "updated_by": "Hardik Vyas",
  "updated_date": "2022-05-30T15:02:56.19",
  "cat_parent_name": "Mens Fashions",
  "cat_main_name": "Fashion and Style",
  "cat_main_id": 2
}
*/

  int? catId;
  int? catParentId;
  String? catName;
  String? catImage;
  bool? catIsActive;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  String? catParentName;
  String? catMainName;
  int? catMainId;

  GetUnderPriceModelDataChildCategory({
    this.catId,
    this.catParentId,
    this.catName,
    this.catImage,
    this.catIsActive,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.catParentName,
    this.catMainName,
    this.catMainId,
  });
  GetUnderPriceModelDataChildCategory.fromJson(Map<String, dynamic> json) {
    catId = json['cat_id']?.toInt();
    catParentId = json['cat_parent_id']?.toInt();
    catName = json['cat_name']?.toString();
    catImage = json['cat_image']?.toString();
    catIsActive = json['cat_is_active'];
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    catParentName = json['cat_parent_name']?.toString();
    catMainName = json['cat_main_name']?.toString();
    catMainId = json['cat_main_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cat_id'] = catId;
    data['cat_parent_id'] = catParentId;
    data['cat_name'] = catName;
    data['cat_image'] = catImage;
    data['cat_is_active'] = catIsActive;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['cat_parent_name'] = catParentName;
    data['cat_main_name'] = catMainName;
    data['cat_main_id'] = catMainId;
    return data;
  }
}

class GetUnderPriceModelData {
/*
{
  "ItemByPrice1": 99,
  "ItemByPrice2": 199,
  "ItemByPrice3": 299,
  "ItemByPrice4": 399,
  "ItemByPrice5": 499,
  "ItemByPrice6": 599,
  "ItemByPrice7": 699,
  "ItemByPrice8": 799,
  "ItemByPrice9": 899,
  "ItemByPrice10": 999,
  "TopDealsMainCatId": 2,
  "TopDealsSubCatId": 7,
  "sub_cat_name": "Mens Fashions",
  "sub_cat_image": "Category_30052022030220.jpg",
  "PlayStoreLink": "https://www.playstore.com/",
  "AppStoreLink": "https://www.apple.com/app-store/",
  "TwitterLink": "http://twitter.com/",
  "FacebookLink": "https://facebook.com/",
  "InstagramLink": "http://instagram.com/",
  "LinkedInLink": "https://www.linkedin.com/",
  "childCategory": [
    {
      "cat_id": 8,
      "cat_parent_id": 7,
      "cat_name": "Tshirts",
      "cat_image": "http://hardik5165-001-site1.itempurl.com/Documents/Category_30052022030255.jpg",
      "cat_is_active": true,
      "created_by": "Hardik Vyas",
      "created_date": "2022-04-30T04:36:38.217",
      "updated_by": "Hardik Vyas",
      "updated_date": "2022-05-30T15:02:56.19",
      "cat_parent_name": "Mens Fashions",
      "cat_main_name": "Fashion and Style",
      "cat_main_id": 2
    }
  ]
}
*/

  int? ItemByPrice1;
  int? ItemByPrice2;
  int? ItemByPrice3;
  int? ItemByPrice4;
  int? ItemByPrice5;
  int? ItemByPrice6;
  int? ItemByPrice7;
  int? ItemByPrice8;
  int? ItemByPrice9;
  int? ItemByPrice10;
  int? TopDealsMainCatId;
  int? TopDealsSubCatId;
  String? subCatName;
  String? subCatImage;
  String? PlayStoreLink;
  String? AppStoreLink;
  String? TwitterLink;
  String? FacebookLink;
  String? InstagramLink;
  String? LinkedInLink;
  List<GetUnderPriceModelDataChildCategory?>? childCategory;

  GetUnderPriceModelData({
    this.ItemByPrice1,
    this.ItemByPrice2,
    this.ItemByPrice3,
    this.ItemByPrice4,
    this.ItemByPrice5,
    this.ItemByPrice6,
    this.ItemByPrice7,
    this.ItemByPrice8,
    this.ItemByPrice9,
    this.ItemByPrice10,
    this.TopDealsMainCatId,
    this.TopDealsSubCatId,
    this.subCatName,
    this.subCatImage,
    this.PlayStoreLink,
    this.AppStoreLink,
    this.TwitterLink,
    this.FacebookLink,
    this.InstagramLink,
    this.LinkedInLink,
    this.childCategory,
  });
  GetUnderPriceModelData.fromJson(Map<String, dynamic> json) {
    ItemByPrice1 = json['ItemByPrice1']?.toInt();
    ItemByPrice2 = json['ItemByPrice2']?.toInt();
    ItemByPrice3 = json['ItemByPrice3']?.toInt();
    ItemByPrice4 = json['ItemByPrice4']?.toInt();
    ItemByPrice5 = json['ItemByPrice5']?.toInt();
    ItemByPrice6 = json['ItemByPrice6']?.toInt();
    ItemByPrice7 = json['ItemByPrice7']?.toInt();
    ItemByPrice8 = json['ItemByPrice8']?.toInt();
    ItemByPrice9 = json['ItemByPrice9']?.toInt();
    ItemByPrice10 = json['ItemByPrice10']?.toInt();
    TopDealsMainCatId = json['TopDealsMainCatId']?.toInt();
    TopDealsSubCatId = json['TopDealsSubCatId']?.toInt();
    subCatName = json['sub_cat_name']?.toString();
    subCatImage = json['sub_cat_image']?.toString();
    PlayStoreLink = json['PlayStoreLink']?.toString();
    AppStoreLink = json['AppStoreLink']?.toString();
    TwitterLink = json['TwitterLink']?.toString();
    FacebookLink = json['FacebookLink']?.toString();
    InstagramLink = json['InstagramLink']?.toString();
    LinkedInLink = json['LinkedInLink']?.toString();
    if (json['childCategory'] != null) {
      final v = json['childCategory'];
      final arr0 = <GetUnderPriceModelDataChildCategory>[];
      v.forEach((v) {
        arr0.add(GetUnderPriceModelDataChildCategory.fromJson(v));
      });
      childCategory = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ItemByPrice1'] = ItemByPrice1;
    data['ItemByPrice2'] = ItemByPrice2;
    data['ItemByPrice3'] = ItemByPrice3;
    data['ItemByPrice4'] = ItemByPrice4;
    data['ItemByPrice5'] = ItemByPrice5;
    data['ItemByPrice6'] = ItemByPrice6;
    data['ItemByPrice7'] = ItemByPrice7;
    data['ItemByPrice8'] = ItemByPrice8;
    data['ItemByPrice9'] = ItemByPrice9;
    data['ItemByPrice10'] = ItemByPrice10;
    data['TopDealsMainCatId'] = TopDealsMainCatId;
    data['TopDealsSubCatId'] = TopDealsSubCatId;
    data['sub_cat_name'] = subCatName;
    data['sub_cat_image'] = subCatImage;
    data['PlayStoreLink'] = PlayStoreLink;
    data['AppStoreLink'] = AppStoreLink;
    data['TwitterLink'] = TwitterLink;
    data['FacebookLink'] = FacebookLink;
    data['InstagramLink'] = InstagramLink;
    data['LinkedInLink'] = LinkedInLink;
    if (childCategory != null) {
      final v = childCategory;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['childCategory'] = arr0;
    }
    return data;
  }
}

class GetUnderPriceModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": {
    "ItemByPrice1": 99,
    "ItemByPrice2": 199,
    "ItemByPrice3": 299,
    "ItemByPrice4": 399,
    "ItemByPrice5": 499,
    "ItemByPrice6": 599,
    "ItemByPrice7": 699,
    "ItemByPrice8": 799,
    "ItemByPrice9": 899,
    "ItemByPrice10": 999,
    "TopDealsMainCatId": 2,
    "TopDealsSubCatId": 7,
    "sub_cat_name": "Mens Fashions",
    "sub_cat_image": "Category_30052022030220.jpg",
    "PlayStoreLink": "https://www.playstore.com/",
    "AppStoreLink": "https://www.apple.com/app-store/",
    "TwitterLink": "http://twitter.com/",
    "FacebookLink": "https://facebook.com/",
    "InstagramLink": "http://instagram.com/",
    "LinkedInLink": "https://www.linkedin.com/",
    "childCategory": [
      {
        "cat_id": 8,
        "cat_parent_id": 7,
        "cat_name": "Tshirts",
        "cat_image": "http://hardik5165-001-site1.itempurl.com/Documents/Category_30052022030255.jpg",
        "cat_is_active": true,
        "created_by": "Hardik Vyas",
        "created_date": "2022-04-30T04:36:38.217",
        "updated_by": "Hardik Vyas",
        "updated_date": "2022-05-30T15:02:56.19",
        "cat_parent_name": "Mens Fashions",
        "cat_main_name": "Fashion and Style",
        "cat_main_id": 2
      }
    ]
  }
}
*/

  int? Code;
  String? Message;
  GetUnderPriceModelData? Data;

  GetUnderPriceModel({
    this.Code,
    this.Message,
    this.Data,
  });
  GetUnderPriceModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? GetUnderPriceModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
