///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SendOtpModel {
/*
{
  "Code": 1,
  "Message": "",
  "Data": "431759"
}
*/

  int? Code;
  String? Message;
  String? Data;

  SendOtpModel({
    this.Code,
    this.Message,
    this.Data,
  });
  SendOtpModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    Data = json['Data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    data['Data'] = Data;
    return data;
  }
}
