///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetItemReviewModelData {
/*
{
  "creview_id": 1,
  "creview_cus_id": 1,
  "creview_itm_id": 1,
  "creview_isku_id": 1,
  "creview_rating": 3,
  "creview_remark": "Good Quality",
  "creview_image1": "",
  "creview_image2": "",
  "creview_image3": "",
  "creview_created_date": "2022-06-25T07:34:43.82",
  "creview_updated_date": "2022-06-25T07:58:05.467",
  "creview_is_active": true,
  "itm_name": "Polo Tshirt Pure Cotton",
  "primary_var_name": "Size",
  "secondary_var_name": "Colour",
  "primary_varo_name": "S",
  "secondary_varo_name": "Black",
  "cus_first_name": "Hardik",
  "cus_last_name": "Vyas",
  "cus_mobile": "9724558884",
  "cus_email": "vyas.hardik05@gmail.com"
}
*/

  int? creviewId;
  int? creviewCusId;
  int? creviewItmId;
  int? creviewIskuId;
  int? creviewRating;
  String? creviewRemark;
  String? creviewImage1;
  String? creviewImage2;
  String? creviewImage3;
  String? creviewCreatedDate;
  String? creviewUpdatedDate;
  bool? creviewIsActive;
  String? itmName;
  String? primaryVarName;
  String? secondaryVarName;
  String? primaryVaroName;
  String? secondaryVaroName;
  String? cusFirstName;
  String? cusLastName;
  String? cusMobile;
  String? cusEmail;

  GetItemReviewModelData({
    this.creviewId,
    this.creviewCusId,
    this.creviewItmId,
    this.creviewIskuId,
    this.creviewRating,
    this.creviewRemark,
    this.creviewImage1,
    this.creviewImage2,
    this.creviewImage3,
    this.creviewCreatedDate,
    this.creviewUpdatedDate,
    this.creviewIsActive,
    this.itmName,
    this.primaryVarName,
    this.secondaryVarName,
    this.primaryVaroName,
    this.secondaryVaroName,
    this.cusFirstName,
    this.cusLastName,
    this.cusMobile,
    this.cusEmail,
  });
  GetItemReviewModelData.fromJson(Map<String, dynamic> json) {
    creviewId = json['creview_id']?.toInt();
    creviewCusId = json['creview_cus_id']?.toInt();
    creviewItmId = json['creview_itm_id']?.toInt();
    creviewIskuId = json['creview_isku_id']?.toInt();
    creviewRating = json['creview_rating']?.toInt();
    creviewRemark = json['creview_remark']?.toString();
    creviewImage1 = json['creview_image1']?.toString();
    creviewImage2 = json['creview_image2']?.toString();
    creviewImage3 = json['creview_image3']?.toString();
    creviewCreatedDate = json['creview_created_date']?.toString();
    creviewUpdatedDate = json['creview_updated_date']?.toString();
    creviewIsActive = json['creview_is_active'];
    itmName = json['itm_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    primaryVaroName = json['primary_varo_name']?.toString();
    secondaryVaroName = json['secondary_varo_name']?.toString();
    cusFirstName = json['cus_first_name']?.toString();
    cusLastName = json['cus_last_name']?.toString();
    cusMobile = json['cus_mobile']?.toString();
    cusEmail = json['cus_email']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['creview_id'] = creviewId;
    data['creview_cus_id'] = creviewCusId;
    data['creview_itm_id'] = creviewItmId;
    data['creview_isku_id'] = creviewIskuId;
    data['creview_rating'] = creviewRating;
    data['creview_remark'] = creviewRemark;
    data['creview_image1'] = creviewImage1;
    data['creview_image2'] = creviewImage2;
    data['creview_image3'] = creviewImage3;
    data['creview_created_date'] = creviewCreatedDate;
    data['creview_updated_date'] = creviewUpdatedDate;
    data['creview_is_active'] = creviewIsActive;
    data['itm_name'] = itmName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    data['primary_varo_name'] = primaryVaroName;
    data['secondary_varo_name'] = secondaryVaroName;
    data['cus_first_name'] = cusFirstName;
    data['cus_last_name'] = cusLastName;
    data['cus_mobile'] = cusMobile;
    data['cus_email'] = cusEmail;
    return data;
  }
}

class GetItemReviewModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "creview_id": 1,
      "creview_cus_id": 1,
      "creview_itm_id": 1,
      "creview_isku_id": 1,
      "creview_rating": 3,
      "creview_remark": "Good Quality",
      "creview_image1": "",
      "creview_image2": "",
      "creview_image3": "",
      "creview_created_date": "2022-06-25T07:34:43.82",
      "creview_updated_date": "2022-06-25T07:58:05.467",
      "creview_is_active": true,
      "itm_name": "Polo Tshirt Pure Cotton",
      "primary_var_name": "Size",
      "secondary_var_name": "Colour",
      "primary_varo_name": "S",
      "secondary_varo_name": "Black",
      "cus_first_name": "Hardik",
      "cus_last_name": "Vyas",
      "cus_mobile": "9724558884",
      "cus_email": "vyas.hardik05@gmail.com"
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<GetItemReviewModelData?>? Data;

  GetItemReviewModel({
    this.Code,
    this.Message,
    this.Data,
  });
  GetItemReviewModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <GetItemReviewModelData>[];
      v.forEach((v) {
        arr0.add(GetItemReviewModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
