///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetCartModelDataItemListModels {
/*
{
  "itm_id": 1,
  "isku_id": 1,
  "itm_name": "Polo Tshirt Pure Cotton",
  "primary_var_name": "Size",
  "secondary_var_name": "Colour",
  "primary_varo_name": "S",
  "secondary_varo_name": "Black",
  "isku_mrp": 200,
  "isku_offer_price": 0,
  "isku_image_1": "http://rohan4-001-site1.ftempurl.com/DocumentsPUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
  "cart_qty": 1,
  "cart_id": 4
}
*/

  int? itmId;
  int? iskuId;
  String? itmName;
  String? primaryVarName;
  String? secondaryVarName;
  String? primaryVaroName;
  String? secondaryVaroName;
  int? iskuMrp;
  int? iskuOfferPrice;
  String? iskuImage_1;
  int? cartQty;
  int? cartId;

  GetCartModelDataItemListModels({
    this.itmId,
    this.iskuId,
    this.itmName,
    this.primaryVarName,
    this.secondaryVarName,
    this.primaryVaroName,
    this.secondaryVaroName,
    this.iskuMrp,
    this.iskuOfferPrice,
    this.iskuImage_1,
    this.cartQty,
    this.cartId,
  });
  GetCartModelDataItemListModels.fromJson(Map<String, dynamic> json) {
    itmId = json['itm_id']?.toInt();
    iskuId = json['isku_id']?.toInt();
    itmName = json['itm_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    primaryVaroName = json['primary_varo_name']?.toString();
    secondaryVaroName = json['secondary_varo_name']?.toString();
    iskuMrp = json['isku_mrp']?.toInt();
    iskuOfferPrice = json['isku_offer_price']?.toInt();
    iskuImage_1 = json['isku_image_1']?.toString();
    cartQty = json['cart_qty']?.toInt();
    cartId = json['cart_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itm_id'] = itmId;
    data['isku_id'] = iskuId;
    data['itm_name'] = itmName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    data['primary_varo_name'] = primaryVaroName;
    data['secondary_varo_name'] = secondaryVaroName;
    data['isku_mrp'] = iskuMrp;
    data['isku_offer_price'] = iskuOfferPrice;
    data['isku_image_1'] = iskuImage_1;
    data['cart_qty'] = cartQty;
    data['cart_id'] = cartId;
    return data;
  }
}

class GetCartModelData {
/*
{
  "CartTotal": 0,
  "DeliveryCharge": 40,
  "itemListModels": [
    {
      "itm_id": 1,
      "isku_id": 1,
      "itm_name": "Polo Tshirt Pure Cotton",
      "primary_var_name": "Size",
      "secondary_var_name": "Colour",
      "primary_varo_name": "S",
      "secondary_varo_name": "Black",
      "isku_mrp": 200,
      "isku_offer_price": 0,
      "isku_image_1": "http://rohan4-001-site1.ftempurl.com/DocumentsPUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
      "cart_qty": 1,
      "cart_id": 4
    }
  ]
}
*/

  int? CartTotal;
  int? DeliveryCharge;
  List<GetCartModelDataItemListModels?>? itemListModels;

  GetCartModelData({
    this.CartTotal,
    this.DeliveryCharge,
    this.itemListModels,
  });
  GetCartModelData.fromJson(Map<String, dynamic> json) {
    CartTotal = json['CartTotal']?.toInt();
    DeliveryCharge = json['DeliveryCharge']?.toInt();
    if (json['itemListModels'] != null) {
      final v = json['itemListModels'];
      final arr0 = <GetCartModelDataItemListModels>[];
      v.forEach((v) {
        arr0.add(GetCartModelDataItemListModels.fromJson(v));
      });
      itemListModels = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['CartTotal'] = CartTotal;
    data['DeliveryCharge'] = DeliveryCharge;
    if (itemListModels != null) {
      final v = itemListModels;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['itemListModels'] = arr0;
    }
    return data;
  }
}

class GetCartModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": {
    "CartTotal": 0,
    "DeliveryCharge": 40,
    "itemListModels": [
      {
        "itm_id": 1,
        "isku_id": 1,
        "itm_name": "Polo Tshirt Pure Cotton",
        "primary_var_name": "Size",
        "secondary_var_name": "Colour",
        "primary_varo_name": "S",
        "secondary_varo_name": "Black",
        "isku_mrp": 200,
        "isku_offer_price": 0,
        "isku_image_1": "http://rohan4-001-site1.ftempurl.com/DocumentsPUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
        "cart_qty": 1,
        "cart_id": 4
      }
    ]
  }
}
*/

  int? Code;
  String? Message;
  GetCartModelData? Data;

  GetCartModel({
    this.Code,
    this.Message,
    this.Data,
  });
  GetCartModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? GetCartModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
