///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetSuggestedForYouModelData {
/*
{
  "itm_id": 1,
  "isku_id": 1,
  "itm_name": "Polo Tshirt Pure Cotton",
  "primary_var_name": "Size",
  "secondary_var_name": "Colour",
  "primary_varo_name": "S",
  "secondary_varo_name": "Black",
  "isku_mrp": 200,
  "isku_offer_price": 180,
  "isku_image_1": "http://rohan4-001-site1.ftempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
  "cart_qty": 0,
  "cart_id": 0
}
*/

  int? itmId;
  int? iskuId;
  String? itmName;
  String? primaryVarName;
  String? secondaryVarName;
  String? primaryVaroName;
  String? secondaryVaroName;
  int? iskuMrp;
  int? iskuOfferPrice;
  String? iskuImage_1;
  int? cartQty;
  int? cartId;

  GetSuggestedForYouModelData({
    this.itmId,
    this.iskuId,
    this.itmName,
    this.primaryVarName,
    this.secondaryVarName,
    this.primaryVaroName,
    this.secondaryVaroName,
    this.iskuMrp,
    this.iskuOfferPrice,
    this.iskuImage_1,
    this.cartQty,
    this.cartId,
  });
  GetSuggestedForYouModelData.fromJson(Map<String, dynamic> json) {
    itmId = json['itm_id']?.toInt();
    iskuId = json['isku_id']?.toInt();
    itmName = json['itm_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    primaryVaroName = json['primary_varo_name']?.toString();
    secondaryVaroName = json['secondary_varo_name']?.toString();
    iskuMrp = json['isku_mrp']?.toInt();
    iskuOfferPrice = json['isku_offer_price']?.toInt();
    iskuImage_1 = json['isku_image_1']?.toString();
    cartQty = json['cart_qty']?.toInt();
    cartId = json['cart_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itm_id'] = itmId;
    data['isku_id'] = iskuId;
    data['itm_name'] = itmName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    data['primary_varo_name'] = primaryVaroName;
    data['secondary_varo_name'] = secondaryVaroName;
    data['isku_mrp'] = iskuMrp;
    data['isku_offer_price'] = iskuOfferPrice;
    data['isku_image_1'] = iskuImage_1;
    data['cart_qty'] = cartQty;
    data['cart_id'] = cartId;
    return data;
  }
}

class GetSuggestedForYouModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "itm_id": 1,
      "isku_id": 1,
      "itm_name": "Polo Tshirt Pure Cotton",
      "primary_var_name": "Size",
      "secondary_var_name": "Colour",
      "primary_varo_name": "S",
      "secondary_varo_name": "Black",
      "isku_mrp": 200,
      "isku_offer_price": 180,
      "isku_image_1": "http://rohan4-001-site1.ftempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
      "cart_qty": 0,
      "cart_id": 0
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<GetSuggestedForYouModelData?>? Data;

  GetSuggestedForYouModel({
    this.Code,
    this.Message,
    this.Data,
  });
  GetSuggestedForYouModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <GetSuggestedForYouModelData>[];
      v.forEach((v) {
        arr0.add(GetSuggestedForYouModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
