///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetBanner2ModelData {
/*
{
  "bnr_id": 4,
  "bnr_bnrt_id": 2,
  "bnr_name": "Promo 1",
  "bnr_image": "http://hardik5165-001-site1.itempurl.com/Documents/b21_30052022030612.jpg",
  "bnr_valid_from": "2022-05-01T00:00:00",
  "bnr_valid_till": "2022-12-31T00:00:00",
  "bnr_main_cat_id": 0,
  "bnr_sub_cat_id": 7,
  "bnr_child_cat_id": 9,
  "bnr_itm_id": 0,
  "bnr_tags": null,
  "bnr_is_active": true,
  "created_by": "Hardik Vyas",
  "created_date": "2022-05-21T03:29:08.497",
  "updated_by": "Hardik Vyas",
  "updated_date": "2022-05-30T15:06:12.68",
  "bnrt_name": "Home Page Promo Banner 1"
}
*/

  int? bnrId;
  int? bnrBnrtId;
  String? bnrName;
  String? bnrImage;
  String? bnrValidFrom;
  String? bnrValidTill;
  int? bnrMainCatId;
  int? bnrSubCatId;
  int? bnrChildCatId;
  int? bnrItmId;
  String? bnrTags;
  bool? bnrIsActive;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  String? bnrtName;

  GetBanner2ModelData({
    this.bnrId,
    this.bnrBnrtId,
    this.bnrName,
    this.bnrImage,
    this.bnrValidFrom,
    this.bnrValidTill,
    this.bnrMainCatId,
    this.bnrSubCatId,
    this.bnrChildCatId,
    this.bnrItmId,
    this.bnrTags,
    this.bnrIsActive,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.bnrtName,
  });
  GetBanner2ModelData.fromJson(Map<String, dynamic> json) {
    bnrId = json['bnr_id']?.toInt();
    bnrBnrtId = json['bnr_bnrt_id']?.toInt();
    bnrName = json['bnr_name']?.toString();
    bnrImage = json['bnr_image']?.toString();
    bnrValidFrom = json['bnr_valid_from']?.toString();
    bnrValidTill = json['bnr_valid_till']?.toString();
    bnrMainCatId = json['bnr_main_cat_id']?.toInt();
    bnrSubCatId = json['bnr_sub_cat_id']?.toInt();
    bnrChildCatId = json['bnr_child_cat_id']?.toInt();
    bnrItmId = json['bnr_itm_id']?.toInt();
    bnrTags = json['bnr_tags']?.toString();
    bnrIsActive = json['bnr_is_active'];
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    bnrtName = json['bnrt_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bnr_id'] = bnrId;
    data['bnr_bnrt_id'] = bnrBnrtId;
    data['bnr_name'] = bnrName;
    data['bnr_image'] = bnrImage;
    data['bnr_valid_from'] = bnrValidFrom;
    data['bnr_valid_till'] = bnrValidTill;
    data['bnr_main_cat_id'] = bnrMainCatId;
    data['bnr_sub_cat_id'] = bnrSubCatId;
    data['bnr_child_cat_id'] = bnrChildCatId;
    data['bnr_itm_id'] = bnrItmId;
    data['bnr_tags'] = bnrTags;
    data['bnr_is_active'] = bnrIsActive;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['bnrt_name'] = bnrtName;
    return data;
  }
}

class GetBanner2Model {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "bnr_id": 4,
      "bnr_bnrt_id": 2,
      "bnr_name": "Promo 1",
      "bnr_image": "http://hardik5165-001-site1.itempurl.com/Documents/b21_30052022030612.jpg",
      "bnr_valid_from": "2022-05-01T00:00:00",
      "bnr_valid_till": "2022-12-31T00:00:00",
      "bnr_main_cat_id": 0,
      "bnr_sub_cat_id": 7,
      "bnr_child_cat_id": 9,
      "bnr_itm_id": 0,
      "bnr_tags": null,
      "bnr_is_active": true,
      "created_by": "Hardik Vyas",
      "created_date": "2022-05-21T03:29:08.497",
      "updated_by": "Hardik Vyas",
      "updated_date": "2022-05-30T15:06:12.68",
      "bnrt_name": "Home Page Promo Banner 1"
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<GetBanner2ModelData?>? Data;

  GetBanner2Model({
    this.Code,
    this.Message,
    this.Data,
  });
  GetBanner2Model.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <GetBanner2ModelData>[];
      v.forEach((v) {
        arr0.add(GetBanner2ModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
