///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetBannerforHomePageModelData {
/*
{
  "bnr_id": 1,
  "bnr_bnrt_id": 1,
  "bnr_name": "Test Test12",
  "bnr_image": "http://hardik5165-001-site1.itempurl.com/Documents/Homepage-Banner-3-(2240x614)_2_29052022083611.gif",
  "bnr_valid_from": "2022-05-29T00:00:00",
  "bnr_valid_till": "2022-05-30T00:00:00",
  "bnr_is_active": true,
  "created_by": "Hardik Vyas",
  "created_date": "2022-05-09T06:46:19.29",
  "updated_by": "Hardik Vyas",
  "updated_date": "2022-05-29T08:36:11.657",
  "bnrt_name": "Home Page Main Banner"
}
*/

  int? bnrId;
  int? bnrBnrtId;
  String? bnrName;
  String? bnrImage;
  String? bnrValidFrom;
  String? bnrValidTill;
  bool? bnrIsActive;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  String? bnrtName;

  GetBannerforHomePageModelData({
    this.bnrId,
    this.bnrBnrtId,
    this.bnrName,
    this.bnrImage,
    this.bnrValidFrom,
    this.bnrValidTill,
    this.bnrIsActive,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.bnrtName,
  });
  GetBannerforHomePageModelData.fromJson(Map<String, dynamic> json) {
    bnrId = json['bnr_id']?.toInt();
    bnrBnrtId = json['bnr_bnrt_id']?.toInt();
    bnrName = json['bnr_name']?.toString();
    bnrImage = json['bnr_image']?.toString();
    bnrValidFrom = json['bnr_valid_from']?.toString();
    bnrValidTill = json['bnr_valid_till']?.toString();
    bnrIsActive = json['bnr_is_active'];
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    bnrtName = json['bnrt_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bnr_id'] = bnrId;
    data['bnr_bnrt_id'] = bnrBnrtId;
    data['bnr_name'] = bnrName;
    data['bnr_image'] = bnrImage;
    data['bnr_valid_from'] = bnrValidFrom;
    data['bnr_valid_till'] = bnrValidTill;
    data['bnr_is_active'] = bnrIsActive;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['bnrt_name'] = bnrtName;
    return data;
  }
}

class GetBannerforHomePageModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": [
    {
      "bnr_id": 1,
      "bnr_bnrt_id": 1,
      "bnr_name": "Test Test12",
      "bnr_image": "http://hardik5165-001-site1.itempurl.com/Documents/Homepage-Banner-3-(2240x614)_2_29052022083611.gif",
      "bnr_valid_from": "2022-05-29T00:00:00",
      "bnr_valid_till": "2022-05-30T00:00:00",
      "bnr_is_active": true,
      "created_by": "Hardik Vyas",
      "created_date": "2022-05-09T06:46:19.29",
      "updated_by": "Hardik Vyas",
      "updated_date": "2022-05-29T08:36:11.657",
      "bnrt_name": "Home Page Main Banner"
    }
  ]
}
*/

  int? Code;
  String? Message;
  List<GetBannerforHomePageModelData?>? Data;

  GetBannerforHomePageModel({
    this.Code,
    this.Message,
    this.Data,
  });
  GetBannerforHomePageModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <GetBannerforHomePageModelData>[];
      v.forEach((v) {
        arr0.add(GetBannerforHomePageModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
