///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductDetailsModelDataItemSkuDetailsModelsItemVariationDetailsModels {
/*
{
  "isku_id": 1,
  "isku_itm_id": 0,
  "isku_primary_varo_id": 0,
  "isku_secondary_varo_id": 0,
  "isku_uom_id": 0,
  "isku_images": [
    "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg"
  ],
  "isku_image_1": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
  "isku_image_2": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (3)_12062022063028.jpg",
  "isku_image_3": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_12062022063029.jpg",
  "isku_image_4": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (1)_10062022120100.jpg",
  "isku_image_5": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_09062022120714.jpg",
  "isku_mrp": 200,
  "isku_offer_price": 180,
  "isku_is_active": null,
  "is_variant_available": null,
  "created_by": null,
  "created_date": null,
  "updated_by": null,
  "updated_date": null,
  "itm_name": null,
  "primary_var_name": null,
  "secondary_var_name": null,
  "primary_varo_name": null,
  "secondary_varo_name": "Black",
  "idod_valid_from": null,
  "idod_valid_to": null,
  "idod_is_active": null,
  "ifeat_valid_from": null,
  "ifeat_valid_to": null,
  "ifeat_is_active": null,
  "cat_name": null,
  "itemVariationDetailsModels": null,
  "sstk_seller_id": 0,
  "sstk_qty": null
}
*/

  int? iskuId;
  int? iskuItmId;
  int? iskuPrimaryVaroId;
  int? iskuSecondaryVaroId;
  int? iskuUomId;
  List<String?>? iskuImages;
  String? iskuImage_1;
  String? iskuImage_2;
  String? iskuImage_3;
  String? iskuImage_4;
  String? iskuImage_5;
  int? iskuMrp;
  int? iskuOfferPrice;
  String? iskuIsActive;
  String? isVariantAvailable;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  String? itmName;
  String? primaryVarName;
  String? secondaryVarName;
  String? primaryVaroName;
  String? secondaryVaroName;
  String? idodValidFrom;
  String? idodValidTo;
  String? idodIsActive;
  String? ifeatValidFrom;
  String? ifeatValidTo;
  String? ifeatIsActive;
  String? catName;
  String? itemVariationDetailsModels;
  int? sstkSellerId;
  String? sstkQty;

  ProductDetailsModelDataItemSkuDetailsModelsItemVariationDetailsModels({
    this.iskuId,
    this.iskuItmId,
    this.iskuPrimaryVaroId,
    this.iskuSecondaryVaroId,
    this.iskuUomId,
    this.iskuImages,
    this.iskuImage_1,
    this.iskuImage_2,
    this.iskuImage_3,
    this.iskuImage_4,
    this.iskuImage_5,
    this.iskuMrp,
    this.iskuOfferPrice,
    this.iskuIsActive,
    this.isVariantAvailable,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.itmName,
    this.primaryVarName,
    this.secondaryVarName,
    this.primaryVaroName,
    this.secondaryVaroName,
    this.idodValidFrom,
    this.idodValidTo,
    this.idodIsActive,
    this.ifeatValidFrom,
    this.ifeatValidTo,
    this.ifeatIsActive,
    this.catName,
    this.itemVariationDetailsModels,
    this.sstkSellerId,
    this.sstkQty,
  });
  ProductDetailsModelDataItemSkuDetailsModelsItemVariationDetailsModels.fromJson(Map<String, dynamic> json) {
    iskuId = json['isku_id']?.toInt();
    iskuItmId = json['isku_itm_id']?.toInt();
    iskuPrimaryVaroId = json['isku_primary_varo_id']?.toInt();
    iskuSecondaryVaroId = json['isku_secondary_varo_id']?.toInt();
    iskuUomId = json['isku_uom_id']?.toInt();
    if (json['isku_images'] != null) {
      final v = json['isku_images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      iskuImages = arr0;
    }
    iskuImage_1 = json['isku_image_1']?.toString();
    iskuImage_2 = json['isku_image_2']?.toString();
    iskuImage_3 = json['isku_image_3']?.toString();
    iskuImage_4 = json['isku_image_4']?.toString();
    iskuImage_5 = json['isku_image_5']?.toString();
    iskuMrp = json['isku_mrp']?.toInt();
    iskuOfferPrice = json['isku_offer_price']?.toInt();
    iskuIsActive = json['isku_is_active']?.toString();
    isVariantAvailable = json['is_variant_available']?.toString();
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    itmName = json['itm_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    primaryVaroName = json['primary_varo_name']?.toString();
    secondaryVaroName = json['secondary_varo_name']?.toString();
    idodValidFrom = json['idod_valid_from']?.toString();
    idodValidTo = json['idod_valid_to']?.toString();
    idodIsActive = json['idod_is_active']?.toString();
    ifeatValidFrom = json['ifeat_valid_from']?.toString();
    ifeatValidTo = json['ifeat_valid_to']?.toString();
    ifeatIsActive = json['ifeat_is_active']?.toString();
    catName = json['cat_name']?.toString();
    itemVariationDetailsModels = json['itemVariationDetailsModels']?.toString();
    sstkSellerId = json['sstk_seller_id']?.toInt();
    sstkQty = json['sstk_qty']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isku_id'] = iskuId;
    data['isku_itm_id'] = iskuItmId;
    data['isku_primary_varo_id'] = iskuPrimaryVaroId;
    data['isku_secondary_varo_id'] = iskuSecondaryVaroId;
    data['isku_uom_id'] = iskuUomId;
    if (iskuImages != null) {
      final v = iskuImages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['isku_images'] = arr0;
    }
    data['isku_image_1'] = iskuImage_1;
    data['isku_image_2'] = iskuImage_2;
    data['isku_image_3'] = iskuImage_3;
    data['isku_image_4'] = iskuImage_4;
    data['isku_image_5'] = iskuImage_5;
    data['isku_mrp'] = iskuMrp;
    data['isku_offer_price'] = iskuOfferPrice;
    data['isku_is_active'] = iskuIsActive;
    data['is_variant_available'] = isVariantAvailable;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['itm_name'] = itmName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    data['primary_varo_name'] = primaryVaroName;
    data['secondary_varo_name'] = secondaryVaroName;
    data['idod_valid_from'] = idodValidFrom;
    data['idod_valid_to'] = idodValidTo;
    data['idod_is_active'] = idodIsActive;
    data['ifeat_valid_from'] = ifeatValidFrom;
    data['ifeat_valid_to'] = ifeatValidTo;
    data['ifeat_is_active'] = ifeatIsActive;
    data['cat_name'] = catName;
    data['itemVariationDetailsModels'] = itemVariationDetailsModels;
    data['sstk_seller_id'] = sstkSellerId;
    data['sstk_qty'] = sstkQty;
    return data;
  }
}

class ProductDetailsModelDataItemSkuDetailsModels {
/*
{
  "isku_id": 1,
  "isku_itm_id": 0,
  "isku_primary_varo_id": 0,
  "isku_secondary_varo_id": 0,
  "isku_uom_id": 0,
  "isku_images": [
    "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg"
  ],
  "isku_image_1": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
  "isku_image_2": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (3)_12062022063028.jpg",
  "isku_image_3": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_12062022063029.jpg",
  "isku_image_4": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (1)_10062022120100.jpg",
  "isku_image_5": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_09062022120714.jpg",
  "isku_mrp": 200,
  "isku_offer_price": 180,
  "isku_is_active": null,
  "is_variant_available": true,
  "created_by": null,
  "created_date": null,
  "updated_by": null,
  "updated_date": null,
  "itm_name": null,
  "primary_var_name": null,
  "secondary_var_name": "Colour",
  "primary_varo_name": "S",
  "secondary_varo_name": null,
  "idod_valid_from": null,
  "idod_valid_to": null,
  "idod_is_active": null,
  "ifeat_valid_from": null,
  "ifeat_valid_to": null,
  "ifeat_is_active": null,
  "cat_name": null,
  "itemVariationDetailsModels": [
    {
      "isku_id": 1,
      "isku_itm_id": 0,
      "isku_primary_varo_id": 0,
      "isku_secondary_varo_id": 0,
      "isku_uom_id": 0,
      "isku_images": [
        "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg"
      ],
      "isku_image_1": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
      "isku_image_2": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (3)_12062022063028.jpg",
      "isku_image_3": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_12062022063029.jpg",
      "isku_image_4": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (1)_10062022120100.jpg",
      "isku_image_5": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_09062022120714.jpg",
      "isku_mrp": 200,
      "isku_offer_price": 180,
      "isku_is_active": null,
      "is_variant_available": null,
      "created_by": null,
      "created_date": null,
      "updated_by": null,
      "updated_date": null,
      "itm_name": null,
      "primary_var_name": null,
      "secondary_var_name": null,
      "primary_varo_name": null,
      "secondary_varo_name": "Black",
      "idod_valid_from": null,
      "idod_valid_to": null,
      "idod_is_active": null,
      "ifeat_valid_from": null,
      "ifeat_valid_to": null,
      "ifeat_is_active": null,
      "cat_name": null,
      "itemVariationDetailsModels": null,
      "sstk_seller_id": 0,
      "sstk_qty": null
    }
  ],
  "sstk_seller_id": 0,
  "sstk_qty": null
}
*/

  int? iskuId;
  int? iskuItmId;
  int? iskuPrimaryVaroId;
  int? iskuSecondaryVaroId;
  int? iskuUomId;
  List<String?>? iskuImages;
  String? iskuImage_1;
  String? iskuImage_2;
  String? iskuImage_3;
  String? iskuImage_4;
  String? iskuImage_5;
  int? iskuMrp;
  int? iskuOfferPrice;
  String? iskuIsActive;
  bool? isVariantAvailable;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  String? itmName;
  String? primaryVarName;
  String? secondaryVarName;
  String? primaryVaroName;
  String? secondaryVaroName;
  String? idodValidFrom;
  String? idodValidTo;
  String? idodIsActive;
  String? ifeatValidFrom;
  String? ifeatValidTo;
  String? ifeatIsActive;
  String? catName;
  List<ProductDetailsModelDataItemSkuDetailsModelsItemVariationDetailsModels?>? itemVariationDetailsModels;
  int? sstkSellerId;
  String? sstkQty;

  ProductDetailsModelDataItemSkuDetailsModels({
    this.iskuId,
    this.iskuItmId,
    this.iskuPrimaryVaroId,
    this.iskuSecondaryVaroId,
    this.iskuUomId,
    this.iskuImages,
    this.iskuImage_1,
    this.iskuImage_2,
    this.iskuImage_3,
    this.iskuImage_4,
    this.iskuImage_5,
    this.iskuMrp,
    this.iskuOfferPrice,
    this.iskuIsActive,
    this.isVariantAvailable,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.itmName,
    this.primaryVarName,
    this.secondaryVarName,
    this.primaryVaroName,
    this.secondaryVaroName,
    this.idodValidFrom,
    this.idodValidTo,
    this.idodIsActive,
    this.ifeatValidFrom,
    this.ifeatValidTo,
    this.ifeatIsActive,
    this.catName,
    this.itemVariationDetailsModels,
    this.sstkSellerId,
    this.sstkQty,
  });
  ProductDetailsModelDataItemSkuDetailsModels.fromJson(Map<String, dynamic> json) {
    iskuId = json['isku_id']?.toInt();
    iskuItmId = json['isku_itm_id']?.toInt();
    iskuPrimaryVaroId = json['isku_primary_varo_id']?.toInt();
    iskuSecondaryVaroId = json['isku_secondary_varo_id']?.toInt();
    iskuUomId = json['isku_uom_id']?.toInt();
    if (json['isku_images'] != null) {
      final v = json['isku_images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      iskuImages = arr0;
    }
    iskuImage_1 = json['isku_image_1']?.toString();
    iskuImage_2 = json['isku_image_2']?.toString();
    iskuImage_3 = json['isku_image_3']?.toString();
    iskuImage_4 = json['isku_image_4']?.toString();
    iskuImage_5 = json['isku_image_5']?.toString();
    iskuMrp = json['isku_mrp']?.toInt();
    iskuOfferPrice = json['isku_offer_price']?.toInt();
    iskuIsActive = json['isku_is_active']?.toString();
    isVariantAvailable = json['is_variant_available'];
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    itmName = json['itm_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    primaryVaroName = json['primary_varo_name']?.toString();
    secondaryVaroName = json['secondary_varo_name']?.toString();
    idodValidFrom = json['idod_valid_from']?.toString();
    idodValidTo = json['idod_valid_to']?.toString();
    idodIsActive = json['idod_is_active']?.toString();
    ifeatValidFrom = json['ifeat_valid_from']?.toString();
    ifeatValidTo = json['ifeat_valid_to']?.toString();
    ifeatIsActive = json['ifeat_is_active']?.toString();
    catName = json['cat_name']?.toString();
    if (json['itemVariationDetailsModels'] != null) {
      final v = json['itemVariationDetailsModels'];
      final arr0 = <ProductDetailsModelDataItemSkuDetailsModelsItemVariationDetailsModels>[];
      v.forEach((v) {
        arr0.add(ProductDetailsModelDataItemSkuDetailsModelsItemVariationDetailsModels.fromJson(v));
      });
      itemVariationDetailsModels = arr0;
    }
    sstkSellerId = json['sstk_seller_id']?.toInt();
    sstkQty = json['sstk_qty']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isku_id'] = iskuId;
    data['isku_itm_id'] = iskuItmId;
    data['isku_primary_varo_id'] = iskuPrimaryVaroId;
    data['isku_secondary_varo_id'] = iskuSecondaryVaroId;
    data['isku_uom_id'] = iskuUomId;
    if (iskuImages != null) {
      final v = iskuImages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['isku_images'] = arr0;
    }
    data['isku_image_1'] = iskuImage_1;
    data['isku_image_2'] = iskuImage_2;
    data['isku_image_3'] = iskuImage_3;
    data['isku_image_4'] = iskuImage_4;
    data['isku_image_5'] = iskuImage_5;
    data['isku_mrp'] = iskuMrp;
    data['isku_offer_price'] = iskuOfferPrice;
    data['isku_is_active'] = iskuIsActive;
    data['is_variant_available'] = isVariantAvailable;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['itm_name'] = itmName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    data['primary_varo_name'] = primaryVaroName;
    data['secondary_varo_name'] = secondaryVaroName;
    data['idod_valid_from'] = idodValidFrom;
    data['idod_valid_to'] = idodValidTo;
    data['idod_is_active'] = idodIsActive;
    data['ifeat_valid_from'] = ifeatValidFrom;
    data['ifeat_valid_to'] = ifeatValidTo;
    data['ifeat_is_active'] = ifeatIsActive;
    data['cat_name'] = catName;
    if (itemVariationDetailsModels != null) {
      final v = itemVariationDetailsModels;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['itemVariationDetailsModels'] = arr0;
    }
    data['sstk_seller_id'] = sstkSellerId;
    data['sstk_qty'] = sstkQty;
    return data;
  }
}

class ProductDetailsModelData {
/*
{
  "itm_id": 1,
  "itm_cat_id": 8,
  "itm_name": "Polo Tshirt Pure Cotton",
  "itm_description": "",
  "itm_highlights": "",
  "itm_specifications": "",
  "itm_warranty": "",
  "itm_cmp_id": 1,
  "itm_brand_id": 1,
  "itm_primary_var_id": 1,
  "itm_secondary_var_id": 2,
  "itm_key_features": "",
  "itm_country_of_origin": "India",
  "itm_disclaimer": "Don't wash in machine",
  "itm_is_active": true,
  "created_by": null,
  "created_date": null,
  "updated_by": null,
  "updated_date": null,
  "sub_cat_id": 7,
  "main_cat_id": 2,
  "itm_tags": null,
  "cat_name": null,
  "primary_var_name": "Size",
  "secondary_var_name": "Colour",
  "itemSkuDetailsModels": [
    {
      "isku_id": 1,
      "isku_itm_id": 0,
      "isku_primary_varo_id": 0,
      "isku_secondary_varo_id": 0,
      "isku_uom_id": 0,
      "isku_images": [
        "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg"
      ],
      "isku_image_1": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
      "isku_image_2": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (3)_12062022063028.jpg",
      "isku_image_3": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_12062022063029.jpg",
      "isku_image_4": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (1)_10062022120100.jpg",
      "isku_image_5": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_09062022120714.jpg",
      "isku_mrp": 200,
      "isku_offer_price": 180,
      "isku_is_active": null,
      "is_variant_available": true,
      "created_by": null,
      "created_date": null,
      "updated_by": null,
      "updated_date": null,
      "itm_name": null,
      "primary_var_name": null,
      "secondary_var_name": "Colour",
      "primary_varo_name": "S",
      "secondary_varo_name": null,
      "idod_valid_from": null,
      "idod_valid_to": null,
      "idod_is_active": null,
      "ifeat_valid_from": null,
      "ifeat_valid_to": null,
      "ifeat_is_active": null,
      "cat_name": null,
      "itemVariationDetailsModels": [
        {
          "isku_id": 1,
          "isku_itm_id": 0,
          "isku_primary_varo_id": 0,
          "isku_secondary_varo_id": 0,
          "isku_uom_id": 0,
          "isku_images": [
            "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg"
          ],
          "isku_image_1": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
          "isku_image_2": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (3)_12062022063028.jpg",
          "isku_image_3": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_12062022063029.jpg",
          "isku_image_4": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (1)_10062022120100.jpg",
          "isku_image_5": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_09062022120714.jpg",
          "isku_mrp": 200,
          "isku_offer_price": 180,
          "isku_is_active": null,
          "is_variant_available": null,
          "created_by": null,
          "created_date": null,
          "updated_by": null,
          "updated_date": null,
          "itm_name": null,
          "primary_var_name": null,
          "secondary_var_name": null,
          "primary_varo_name": null,
          "secondary_varo_name": "Black",
          "idod_valid_from": null,
          "idod_valid_to": null,
          "idod_is_active": null,
          "ifeat_valid_from": null,
          "ifeat_valid_to": null,
          "ifeat_is_active": null,
          "cat_name": null,
          "itemVariationDetailsModels": null,
          "sstk_seller_id": 0,
          "sstk_qty": null
        }
      ],
      "sstk_seller_id": 0,
      "sstk_qty": null
    }
  ]
}
*/

  int? itmId;
  int? itmCatId;
  String? itmName;
  String? itmDescription;
  String? itmHighlights;
  String? itmSpecifications;
  String? itmWarranty;
  int? itmCmpId;
  int? itmBrandId;
  int? itmPrimaryVarId;
  int? itmSecondaryVarId;
  String? itmKeyFeatures;
  String? itmCountryOfOrigin;
  String? itmDisclaimer;
  bool? itmIsActive;
  String? createdBy;
  String? createdDate;
  String? updatedBy;
  String? updatedDate;
  int? subCatId;
  int? mainCatId;
  String? itmTags;
  String? catName;
  String? primaryVarName;
  String? secondaryVarName;
  List<ProductDetailsModelDataItemSkuDetailsModels?>? itemSkuDetailsModels;

  ProductDetailsModelData({
    this.itmId,
    this.itmCatId,
    this.itmName,
    this.itmDescription,
    this.itmHighlights,
    this.itmSpecifications,
    this.itmWarranty,
    this.itmCmpId,
    this.itmBrandId,
    this.itmPrimaryVarId,
    this.itmSecondaryVarId,
    this.itmKeyFeatures,
    this.itmCountryOfOrigin,
    this.itmDisclaimer,
    this.itmIsActive,
    this.createdBy,
    this.createdDate,
    this.updatedBy,
    this.updatedDate,
    this.subCatId,
    this.mainCatId,
    this.itmTags,
    this.catName,
    this.primaryVarName,
    this.secondaryVarName,
    this.itemSkuDetailsModels,
  });
  ProductDetailsModelData.fromJson(Map<String, dynamic> json) {
    itmId = json['itm_id']?.toInt();
    itmCatId = json['itm_cat_id']?.toInt();
    itmName = json['itm_name']?.toString();
    itmDescription = json['itm_description']?.toString();
    itmHighlights = json['itm_highlights']?.toString();
    itmSpecifications = json['itm_specifications']?.toString();
    itmWarranty = json['itm_warranty']?.toString();
    itmCmpId = json['itm_cmp_id']?.toInt();
    itmBrandId = json['itm_brand_id']?.toInt();
    itmPrimaryVarId = json['itm_primary_var_id']?.toInt();
    itmSecondaryVarId = json['itm_secondary_var_id']?.toInt();
    itmKeyFeatures = json['itm_key_features']?.toString();
    itmCountryOfOrigin = json['itm_country_of_origin']?.toString();
    itmDisclaimer = json['itm_disclaimer']?.toString();
    itmIsActive = json['itm_is_active'];
    createdBy = json['created_by']?.toString();
    createdDate = json['created_date']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    subCatId = json['sub_cat_id']?.toInt();
    mainCatId = json['main_cat_id']?.toInt();
    itmTags = json['itm_tags']?.toString();
    catName = json['cat_name']?.toString();
    primaryVarName = json['primary_var_name']?.toString();
    secondaryVarName = json['secondary_var_name']?.toString();
    if (json['itemSkuDetailsModels'] != null) {
      final v = json['itemSkuDetailsModels'];
      final arr0 = <ProductDetailsModelDataItemSkuDetailsModels>[];
      v.forEach((v) {
        arr0.add(ProductDetailsModelDataItemSkuDetailsModels.fromJson(v));
      });
      itemSkuDetailsModels = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itm_id'] = itmId;
    data['itm_cat_id'] = itmCatId;
    data['itm_name'] = itmName;
    data['itm_description'] = itmDescription;
    data['itm_highlights'] = itmHighlights;
    data['itm_specifications'] = itmSpecifications;
    data['itm_warranty'] = itmWarranty;
    data['itm_cmp_id'] = itmCmpId;
    data['itm_brand_id'] = itmBrandId;
    data['itm_primary_var_id'] = itmPrimaryVarId;
    data['itm_secondary_var_id'] = itmSecondaryVarId;
    data['itm_key_features'] = itmKeyFeatures;
    data['itm_country_of_origin'] = itmCountryOfOrigin;
    data['itm_disclaimer'] = itmDisclaimer;
    data['itm_is_active'] = itmIsActive;
    data['created_by'] = createdBy;
    data['created_date'] = createdDate;
    data['updated_by'] = updatedBy;
    data['updated_date'] = updatedDate;
    data['sub_cat_id'] = subCatId;
    data['main_cat_id'] = mainCatId;
    data['itm_tags'] = itmTags;
    data['cat_name'] = catName;
    data['primary_var_name'] = primaryVarName;
    data['secondary_var_name'] = secondaryVarName;
    if (itemSkuDetailsModels != null) {
      final v = itemSkuDetailsModels;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['itemSkuDetailsModels'] = arr0;
    }
    return data;
  }
}

class ProductDetailsModel {
/*
{
  "Code": 1,
  "Message": null,
  "Data": {
    "itm_id": 1,
    "itm_cat_id": 8,
    "itm_name": "Polo Tshirt Pure Cotton",
    "itm_description": "",
    "itm_highlights": "",
    "itm_specifications": "",
    "itm_warranty": "",
    "itm_cmp_id": 1,
    "itm_brand_id": 1,
    "itm_primary_var_id": 1,
    "itm_secondary_var_id": 2,
    "itm_key_features": "",
    "itm_country_of_origin": "India",
    "itm_disclaimer": "Don't wash in machine",
    "itm_is_active": true,
    "created_by": null,
    "created_date": null,
    "updated_by": null,
    "updated_date": null,
    "sub_cat_id": 7,
    "main_cat_id": 2,
    "itm_tags": null,
    "cat_name": null,
    "primary_var_name": "Size",
    "secondary_var_name": "Colour",
    "itemSkuDetailsModels": [
      {
        "isku_id": 1,
        "isku_itm_id": 0,
        "isku_primary_varo_id": 0,
        "isku_secondary_varo_id": 0,
        "isku_uom_id": 0,
        "isku_images": [
          "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg"
        ],
        "isku_image_1": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
        "isku_image_2": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (3)_12062022063028.jpg",
        "isku_image_3": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_12062022063029.jpg",
        "isku_image_4": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (1)_10062022120100.jpg",
        "isku_image_5": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_09062022120714.jpg",
        "isku_mrp": 200,
        "isku_offer_price": 180,
        "isku_is_active": null,
        "is_variant_available": true,
        "created_by": null,
        "created_date": null,
        "updated_by": null,
        "updated_date": null,
        "itm_name": null,
        "primary_var_name": null,
        "secondary_var_name": "Colour",
        "primary_varo_name": "S",
        "secondary_varo_name": null,
        "idod_valid_from": null,
        "idod_valid_to": null,
        "idod_is_active": null,
        "ifeat_valid_from": null,
        "ifeat_valid_to": null,
        "ifeat_is_active": null,
        "cat_name": null,
        "itemVariationDetailsModels": [
          {
            "isku_id": 1,
            "isku_itm_id": 0,
            "isku_primary_varo_id": 0,
            "isku_secondary_varo_id": 0,
            "isku_uom_id": 0,
            "isku_images": [
              "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg"
            ],
            "isku_image_1": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt_12062022063027.jpg",
            "isku_image_2": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (3)_12062022063028.jpg",
            "isku_image_3": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_12062022063029.jpg",
            "isku_image_4": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (1)_10062022120100.jpg",
            "isku_image_5": "http://hardik5165-001-site1.itempurl.com/Documents/PUMA-x-BUTTER-GOODS-Men's-Polo-Shirt (5)_09062022120714.jpg",
            "isku_mrp": 200,
            "isku_offer_price": 180,
            "isku_is_active": null,
            "is_variant_available": null,
            "created_by": null,
            "created_date": null,
            "updated_by": null,
            "updated_date": null,
            "itm_name": null,
            "primary_var_name": null,
            "secondary_var_name": null,
            "primary_varo_name": null,
            "secondary_varo_name": "Black",
            "idod_valid_from": null,
            "idod_valid_to": null,
            "idod_is_active": null,
            "ifeat_valid_from": null,
            "ifeat_valid_to": null,
            "ifeat_is_active": null,
            "cat_name": null,
            "itemVariationDetailsModels": null,
            "sstk_seller_id": 0,
            "sstk_qty": null
          }
        ],
        "sstk_seller_id": 0,
        "sstk_qty": null
      }
    ]
  }
}
*/

  int? Code;
  String? Message;
  ProductDetailsModelData? Data;

  ProductDetailsModel({
    this.Code,
    this.Message,
    this.Data,
  });
  ProductDetailsModel.fromJson(Map<String, dynamic> json) {
    Code = json['Code']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? ProductDetailsModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Code'] = Code;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
